### ISSUE TITLE
`install.sh` doesn't work?

### ISSUE THREAD

**Issue by fholmqvist** [oxifinch/budget-helper#9]
```
Disclaimer: Joke.
```

Hello,

I tried installing your app by running `install.sh` but it didn't work?????????????

**Comment by fholmqvist** [comment]
Do I need to change something in the `sqlboiler.toml` file? `init.sql`?

**Comment by oxifinch** [comment]
Fixed and added in PR, here: https://github.com/oxifinch/budget-helper/pull/11
